spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/prueba
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect